# Instances of the Widget CRD from crd.yaml.
apiVersion: kboba.example.com/v1
kind: Widget
metadata:
  name: small-red
  namespace: kboba-demo
spec:
  size: 1
  color: red
---
apiVersion: kboba.example.com/v1
kind: Widget
metadata:
  name: big-blue
  namespace: kboba-demo
spec:
  size: 10
  color: blue
